name: Axe data update
on:
  workflow_dispatch:
  schedule:
    # Run daily, 5:00 UTC - an hour before the WAI site checks for updates
    - cron: '0 5 * * *'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            !**/node_modules/.cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: git fetch
      - run: git checkout act-reports-axe
      ## Make sure we have the latest version of axe-core
      - run: yarn upgrade axe-core@next
      - run: yarn cleanup:core
      - run: yarn report
      - name: Git configure
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: git add reports/. package.json yarn.lock
      # Commit if there's anything staged
      - run: git diff-index --quiet HEAD || git commit -m "Daily update of axe ACT reports" --no-verify
      - run: git push
